This chapter explains the basic use of the Analysis of variance (ANOVA)
model for analyzing appropriate data. This is commonly (but not always)
obtained through experimentation. To truly learn about the appropriate
analysis of experimental data you will need to consult a suitable
textbook on experimental design.

As there are insufficient data sets in the `datasets` package [@Rpkg-base],
the examples in this chapter draw on data supplied with the
`MASS` package [@Rpkg-MASS]. This package supports a very famous resource
by Venables and Riply, often abbreviated to V\&R. The full reference is:

Venables, W.N. and Ripley, B.D. (1999) <span>*Modern Applied Statistics
with S-PLUS.*</span> Third Edition. Springer.

This book is very useful for many topics in statistics and given the
similarity of the syntax between S-PLUS and R , remains a good resource
for users of R today.

## Data and suitable exploratory graphs

The data used to fit models discussed in this chapter require a single
response variable which is assumed continuous, and one or more
explanatory variables that are discrete valued. More specifically, these
explanatory variables are called "factors"; in an experiment, each observation
takes a preplanned level for each factor under consideration.

## One-way ANOVA

## Model validation using diagnostic plots

Readers should note that the same code was used to generate the residual
analysis plots as would be done for a linear regression model. Note that
the `plot()` command is sensitive to the type of object being
used, and that the set of residual graphs is therefore different to
those created for an `lm` object.

## Two-way ANOVA

There are two different situations where a two-way analysis of variance
is called for. First, a simple randomized complete block design and
second, a factorial experiment with two factors.

### Randomized complete block designs {#RCBAnalysis}

We use the `sleep` data used to show the analysis of paired
data in Section \@ref(PairedSamplesTTest), which has two measurements
on ten individuals. As the two observations on each person are often
thought to be related, we use the known structure of the experiment’s
design to incorporate this knowledge. The individual people are
therefore thought of as a blocking variable. Rather than using the
`attach()` command, we employ the `data` argument inside the `aov()` command. As before, we use the
`summary()` method to present the analysis: 

