This chapter explains the commands needed to conduct a number of
multivariate analyses. Little of the theory behind the various
techniques is given here and the reader is assumed to know that the
analysis they wish to conduct is actually appropriate for their
objectives.

## Exploring multivariate data

## Rescaling your data

It is common to find that one or more of the variables in your
multivariate data set dominate the others in terms of the variability,
just because they are on a different scale. Scaling the variables so
they all have mean of zero and variance of one is common prior to a
number of the techniques that follow in this chapter.

The `scale()` command returns a matrix (check)

## Cluster analysis

## Principal component analysis (PCA)

Kaiser’s criterion

## Factor analysis

## Linear discriminant analysis (LDA)

The `MASS` package is required for producing a linear
discriminant analysis (LDA). It is part of the base installation of R
so we only need to load it before issuing any commands in this section. 

