There are some minor differences between the methods used by the
`summary()` and `fivenum()` commands for the first and
third quartiles. See the relevant help page using `?fivenum` for an explanation.

Knowing how these commands work on simple sets of numbers is very useful
for the more elegant presentations in the following sections.

## Obtaining slightly more elegant summaries

When preparing reports it is unlikely that we would want a single
statistic all that often. Rather, we are usually interested in exposing
patterns or differences within the data. We do this graphically but we
may need to extract the exact quantities plotted in the graph as well.

The `tapply()` and `aggregate()` commands are very
useful for creating tables of results, sometimes referred to as pivot
tables. The `tapply()` command has three arguments; the main
variable of interest, the grouping variable(s), and the function we want
performed on each group within the data. In contrast, the
`aggregate()` command has a slightly different way of relating
the response variable to one or more grouping variables. It is easier to
show how these commands work in action so we’ll use the air quality data
again and present various alternatives and the slightly different
resulting output.

Let’s say we want to know the `mean()` wind speed over the five
months data were collected. We could use 

