will make the data explicitly available to you in your current R
workspace.

We can look for relationships among the variables within this data set
using the techniques described in Chapter \@ref(BasicGraphs). Note
in particular the scatter plot matrix presented in
Figure \@ref(fig:AirQuality-ScatterPlotMatrix).

## The simple regression model

To obtain the equation for a straight line relationship of the form
$$y=\alpha+\beta{}x +\varepsilon$$ we use the `lm()` command. The first argument
for this command is a `formula` which is the main component of
any `lm()` command you issue. It is of the form
`y~x` where the *y* is the response variable
and the *x* is the predictor variable. We will see how to modify the
right hand side of the `formula` in subsequent sections. The
$\varepsilon$ is the error term for our model; we look at that aspect
more in Section \@ref(RegValid) below.

```{r include=FALSE}
BlindOrSightedText = ifelse(Blind, "The above equation is a simpler version than you will see in many textbooks. You might see a subscript on the *y*, *x*, and $\\varepsilon$ when referring to individual observations, but when we refer to the set of response values and the set of predictor values, we are usually thinking of them as vectors; as such, the notation above really should indicate that *y*, *x*, and $\varepsilon$ are vectors. A bold face is often used for vectors and matrices or sometimes vectors are underscored. This additional notation is not used in the current context.",
"")
```

`r BlindOrSightedText` A second common argument is the `data` statement. This means
that the model formula can be stated using variable names from within
the `data.frame` mentioned in the `data` statement. Models to explain the amount of `Ozone` using `Wind` and subsequently `Temp` are as follows. 

