Notice that we have altered the range of values covered by the
*y*-axis using a specific command. The `ylim` has a
corresponding `xlim`  to create limits for the *x*-axis.
Adding one more argument to the `plot()` command will change the plotting from points to lines (shown in
Figure \@ref(fig:AirQuality-LinePlotTemp2) ). Combinations of points and
lines can be obtained (not shown); the user can also alter the style of
the points and lines being printed.

There is a simpler way to generate time series plots which we
demonstrate in Chapter \@ref(TimeSeries). It is easier to augment
this line plot than the time series plot, and in so doing we will gain
an insight into how other plots like the time series plot are created.

## Quantile-quantile plots

The most common quantile-quantile plot we might wish to create is used
to investigate the usefulness of the normal distribution to model a
variable’s distribution. Normal quantiles are created automatically for
the normal quantile plot when it is generated using the
`qqnorm()` command. The default plot for this is shown in
Figure \@ref(fig:AirQuality-NormPlotWind).

If these data were normally distributed, the points on the plot would
lie on a straight line. The `qqline()` command adds the straight
line to the plot to assist with determining the linearity of the points.

```{r include=FALSE}
FigCap="A quantile-quantile plot showing the normality of the wind speed measurements."
```
