This chapter was created using version `r packageVersion("BrailleR")`  of the `BrailleR` package. This version of the package has a number of other packages that
it depends on for functionality. When you make the `BrailleR` package available, you may see a few introduction messages that tell you
about the other packages being loaded. You will also be told about some
default settings for the package that can be altered later to suit your
needs.

If you want to know more about the `BrailleR` package and its
creation, you might like to look over its homepage by issuing the
`BrailleRHome()` command which will take you to the [BrailleR Project homepage.](https://R-Resources.massey.ac.nz/BrailleR)

Once you have read through this chapter, you can check out the rest of
the `BrailleR` package’s features as explained in another
e-book. The title of that e-book is “BrailleR in Action"; you can go to
its homepage from R directly by issuing the `BrailleRInAction()` command which will take you to the front page of the book at
https://R-Resources.massey.ac.nz/BrailleRInAction

## Creating a copy of the R console window {#CreateCopyConsole}

In Chapter \@ref(BlindUse) I mentioned the need to save the content of
the console window to a text file to be able to copy and paste its
content to a report or document. One major feature of the `BrailleR` package is that this functionality can be done easily and efficiently.

There are three types of content printed in the console window.

1.  The commands we type,

2.  The output valid commands generate, and

3.  Any error or warning messages that arise from our commands.

The `sink()` command does not currently record the commands or
the errors and warning messages. It is therefore a valuable tool for
those R users that are confident about the validity of their scripts.

Similarly, the `history()`  command shows a list of all issued
commands, even those that contain errors. N.B. The `BrailleR` package has its own `history()` command that opens the contents
of the command history in a text editor so that it can be read using
screen-reading software.

Saving the commands typed into an R session can be achieved using the
`savehistory()` command, but again, this will include the
commands that generated errors. For example 

